hi
andyhite/technical-assessment pull request #1
Opened 2022-09-01 03:19 UTC by joergbaier

2022-09-01 03:24 UTC, joergbaier commented
plz review
@Christopher-Shea @ahlatimer @ivymarkwell @kellyjacksonio @MrAlexLau

2022-09-01 16:36 UTC, ivymarkwell approved these changes
:shipit:

2022-09-02 05:42 UTC, Christopher-Shea requested changes

2022-09-02 05:42 UTC, Christopher-Shea commented on README.md
> +lol it public
it's

2022-09-04 20:13 UTC, MrAlexLau approved these changes
Would be nice to have specs, but feel free to address in a follow up PR if this is blocking the sprint.

2022-09-06 19:32 UTC, kellyjacksonio commented
LGTM

2022-09-15 03:39 UTC, andyhite commented
Hahahah shit this was an initial commit that I apparently pushed to the wrong remote. This wasn't the final thing...if you want to see the final thing, it's at github.com/shipengine/technical-assessment

And yes it's public on purpose - with enterprise github accounts you're limited to a finite number of license seats, and we don't have enough seats to accommodate adding hundreds of candidates to the org to access a private repo. Submission is via an emailed diff (on the real assessment) so the results aren't visible to other candidates.

Anyway, nice to see all you guys in one place again 😆 I'd love to catch up with everyone.

2022-09-20 04:18 UTC, closed without merging